import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const requiredFiles = [
  "apps/web/app/page.tsx",
  "apps/web/components/work-desk.tsx",
  "apps/api/src/main.ts",
  "apps/api/src/auth/auth.controller.ts",
  "apps/api/src/auth/auth-cookie.ts",
  "apps/api/src/auth/auth.guard.ts",
  "apps/api/src/auth/auth.service.ts",
  "apps/api/src/auth/password.ts",
  "apps/api/src/database/database.service.ts",
  "apps/api/migrations/001_auth_foundation.sql",
  "apps/api/migrations/002_invitation_consent_guest_approval.sql",
  "apps/api/migrations/003_persisted_conversation_core.sql",
  "apps/api/migrations/004_contacts_family_managed_groups.sql",
  "apps/api/migrations/005_media_document_desk.sql",
  "apps/api/migrations/006_schedule_rsvp_reminders.sql",
  "apps/api/migrations/007_livekit_call_core.sql",
  "apps/api/src/invitations/invitation.controller.ts",
  "apps/api/src/invitations/invitation.service.ts",
  "apps/api/src/modules/chat.controller.ts",
  "apps/api/src/modules/conversation.service.ts",
  "apps/api/src/modules/outbox-publisher.service.ts",
  "apps/api/src/modules/chat.gateway.ts",
  "apps/api/src/media/media.controller.ts",
  "apps/api/src/media/media.service.ts",
  "apps/api/src/media/media-inspector.ts",
  "apps/api/src/media/local-object-store.ts",
  "apps/api/src/calls/calls.controller.ts",
  "apps/api/src/calls/calls.service.ts",
  "apps/api/src/calls/livekit-provider.service.ts",
  "apps/web/components/call-desk.tsx",
  "apps/web/components/media-panel.tsx",
  "apps/web/components/pdf-viewer.tsx",
  "apps/desktop/main.cjs",
  "apps/desktop/forge.config.cjs",
  "apps/desktop/scripts/build-runtime.mjs",
  "apps/desktop/scripts/generate-windows-icon.ps1",
  "packages/contracts/src/index.ts",
  "docs/mvp-architecture.md",
  "docs/stage-2b-invitations-consent.md",
  "docs/stage-3-persisted-conversations.md",
  "docs/stage-4-contacts-family-managed-groups.md",
  "docs/stage-5-media-document-desk.md",
  "docs/stage-6b-livekit-call-core.md",
  "docs/schema.sql",
  "AGENTS.md",
  ".agents/skills/hahatalk-feature-stage/SKILL.md",
  ".codex/hooks.json"
];
const requiredTerms = [
  "hub",
  "audienceType",
  "message_audiences",
  "message_deliveries",
  "hub_announcement",
  "projectMessageForViewer",
  "spaces/:spaceId/view",
  "@Controller(\"auth\")",
  "@Post(\"signup\")",
  "@Post(\"login\")",
  "@Get(\"me\")",
  "web_sessions",
  "argon2id",
  "httpOnly: true",
  "AuthSession",
  "MvpSnapshot",
  "POST /messages",
  "POST /invitations",
  "token_digest",
  "invitation_approval_requirements",
  "consent_records",
  "auth/sessions",
  "@Controller(\"media\")",
  "@Post(\"uploads\")",
  "media_upload_sessions",
  "media_grants",
  "fileTypeFromBuffer",
  "LocalObjectStore",
  "private_archive",
  "PdfViewer",
  "messages/:messageId/confirm",
  "clientMessageId",
  "idempotency_keys",
  "outbox_events",
  "message:delivery-updated",
  "typing:updated",
  "confirmMessageRead",
  "CreateAttachmentMessageInput",
  "AI 작업",
  "화면 캡처",
  "utilityProcess.fork",
  "requestSingleInstanceLock",
  "setDisplayMediaRequestHandler",
  "Electron Forge",
  "@Controller(\"calls\")",
  "call_participants",
  "canPublishSources",
  "call:incoming",
];

for (const file of requiredFiles) {
  if (!existsSync(join(root, file))) {
    throw new Error(`Missing required file: ${file}`);
  }
}

const source = [
  readFileSync(join(root, "apps/web/components/work-desk.tsx"), "utf8"),
  readFileSync(join(root, "apps/api/src/modules/chat.controller.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/auth/auth.controller.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/auth/auth-cookie.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/auth/auth.service.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/auth/password.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/database/database.service.ts"), "utf8"),
  readFileSync(join(root, "apps/api/migrations/001_auth_foundation.sql"), "utf8"),
  readFileSync(join(root, "apps/api/migrations/002_invitation_consent_guest_approval.sql"), "utf8"),
  readFileSync(join(root, "apps/api/migrations/003_persisted_conversation_core.sql"), "utf8"),
  readFileSync(join(root, "apps/api/migrations/004_contacts_family_managed_groups.sql"), "utf8"),
  readFileSync(join(root, "apps/api/migrations/005_media_document_desk.sql"), "utf8"),
  readFileSync(join(root, "apps/api/migrations/007_livekit_call_core.sql"), "utf8"),
  readFileSync(join(root, "apps/api/src/invitations/invitation.controller.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/invitations/invitation.service.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/modules/chat.gateway.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/modules/conversation.service.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/modules/outbox-publisher.service.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/media/media.controller.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/media/media.service.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/media/media-inspector.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/media/local-object-store.ts"), "utf8"),
  readFileSync(join(root, "apps/web/components/media-panel.tsx"), "utf8"),
  readFileSync(join(root, "apps/web/components/pdf-viewer.tsx"), "utf8"),
  readFileSync(join(root, "apps/api/src/calls/calls.controller.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/calls/calls.service.ts"), "utf8"),
  readFileSync(join(root, "apps/api/src/calls/livekit-provider.service.ts"), "utf8"),
  readFileSync(join(root, "apps/web/components/call-desk.tsx"), "utf8"),
  readFileSync(join(root, "apps/desktop/main.cjs"), "utf8"),
  readFileSync(join(root, "docs/windows-desktop-runtime.md"), "utf8"),
  readFileSync(join(root, "packages/contracts/src/index.ts"), "utf8"),
  readFileSync(join(root, "docs/mvp-architecture.md"), "utf8"),
  readFileSync(join(root, "docs/stage-2b-invitations-consent.md"), "utf8"),
  readFileSync(join(root, "docs/stage-3-persisted-conversations.md"), "utf8"),
  readFileSync(join(root, "docs/stage-4-contacts-family-managed-groups.md"), "utf8"),
  readFileSync(join(root, "docs/stage-5-media-document-desk.md"), "utf8"),
  readFileSync(join(root, "docs/stage-6b-livekit-call-core.md"), "utf8"),
  readFileSync(join(root, "docs/schema.sql"), "utf8"),
  readFileSync(join(root, "AGENTS.md"), "utf8")
].join("\n");

for (const term of requiredTerms) {
  if (!source.includes(term)) {
    throw new Error(`Smoke term not found: ${term}`);
  }
}

console.log("Smoke check passed: HahaTalk hub privacy, API, governance, and media terms are present.");
